listen: ':9876'
targets:
  http:
    - name: 'google'
      url: 'https://www.google.com/'
      rps: 0.5 # 2 RPS
      timeout: '1s'
    - name: 'kubernetes-internal'
      url: 'http://kubernetes.default.svc'
      rps: 2.0
      timeout: '1s'
      tls_skip_verify: true
  dns:
    - name: 'google'
      domain: 'google.com'
      record_type: 'A'
      rps: 1.0
      timeout: '2s'
    - name: 'health-be-svc'
      domain: 'health-be.monitoring.svc.cluster.local'
      record_type: 'A'
      rps: 1.0
      timeout: '2s'
  k8s:
    enabled: false
    simple-probe:
      - namespace: monitoring
        rps: 1.0



