apiVersion: v2
name: health-exporter
home: https://github.com/snapp-cab/health-exporter
sources:
  - https://github.com/snapp-cab/health-exporter.git
type: application
version: 0.1.0
appVersion: 1.0.0
